version: '3.8'

services:
  lemdiklat-mpi:
    build:
      context: .
      args:
        PUBLIC_API_BASE_URL: ${PUBLIC_API_BASE_URL}
    ports:
      - "3002:3002"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3002
      - HOST=0.0.0.0
    restart: unless-stopped
